### ISSUE TITLE
Can't install drip on django 1.11.5

### ISSUE THREAD

**Issue by suhaboncukcu** [zapier/django-drip#60] opened 2017-09-28 12:19 UTC
[✓] pip install django-drip
[✓] Add 'drip' to your installed apps
[✓] Set DRIP_FROM_EMAIL
[✗] python manage.py migrate drip

```
....
....from django.db.models.related import RelatedObject
ImportError: No module named related
```
--------------------------------
pip                   9.0.1  
Django                1.11.5  
django-drip           0.7.1

**Comment by charettes** [comment] 2017-09-28 13:01
Duplicate of #59.

**Closed by charettes** 2017-09-28 13:01 UTC
